spring.application.name=portalapp
server.port = 7502

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/portal
spring.datasource.username=root
spring.datasource.password=FlorinRTX04
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.session.timeout=30m


twilio.account.sid=AC8b9dac9dcd190e15a40eea920fad0339
twilio.auth.token=7c75e96a76e4ec4b60a0de2951e9e76f
twilio.phone.number=+14155238886


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=8835ae001@smtp-brevo.com
spring.mail.password=qTOB5cKwAZvGdrH4
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
